server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
      firstName: Demo
      
externalTask:
  defaultLockDurationInMillis: 180000
  workerFixedDelayInMillis: 500
  workerInitialDelayInMillis: 1000
  retryCount: 3
  maxTask: 5
  retryTimeOut: 10